### PR TITLE
New desktop utils: lumina-photo

### PR DESCRIPTION
**Pull request by lbartoletti**
I propose this first version for the ticket https://github.com/lumina-desktop/lumina/issues/600 

The application opens and saves the images available via Qt, a printing medium is also present. You can navigate between several images. Zooms (in, out, normal, fit) are present.

It will be necessary to plan evolutions afterwards to improve and refine the tool :wink:

### CODE REVIEW

**Comment by q5sys** [comment]
Thanks for the PR!
I'll pull this down and give it a whirl.  Ken is a little busy with other things, so it might take a bit till he's able to test it himself.

**Comment by q5sys** [comment]
I really like what you've got so far. :)  
I was actually partway through developing this, but then I started to get carried away and I started making more of a photo browser, instead of a simple photo viewer.  I'm glad you did the simple one, I'd have completely forgotten about it. lol

Like all things in software development, things get better with age and effort.  
The only things I think that should be put in place beyond what you already have coded, would be...

+ Double Click : Toggle between Actual size and Fill Graphics View
+ Scroll Wheel : up = zoom in / down = zoom out (from the center of graphics view)
+ Ctrl + Scroll Wheel : down = next image / up = previous image
+ Add Tooltips for the buttons you do have in place
+ Menu > View > reword last entry to "Fit to Window"

**Comment by lbartoletti** [comment]
@q5sys one month later, some modification

>     * Add Tooltips for the buttons you do have in place

Which tooltips are missing?

**Comment by beanpole135** [comment]
Thank you for working on that @lbartoletti !
Feel free to continue working on your tool and sending in updates to it as often as you like!

**Pull request merged**
