### PR TITLE
Support xdg-open

### PR DESCRIPTION
**Pull request by rodlie**
Lumina needs support for xdg-open. These patches depend on https://github.com/freedesktop/xdg-utils/pull/3 to work.

### CODE REVIEW

**Comment by beanpole135** [comment]
I don't want to pull in this change for a couple reasons:
1. If "xdg-open" did not do anything because it needed to show the usage info, it needs to return exit code 1 (error/did not do anything) versus exit code 0 (success/did something). If you are trying to use the exit code on the `lumina-open --help` command to determine if lumina-open exists, then you need to use a different approach. Perhaps a simple alternative would be test command? (`test -x /usr/local/bin/lumina-open`)
2. The standardized environment variables for "announcing" which desktop is currently running is already in place (XDG_CURRENT_DESKTOP) as well as the older standard which some login managers still use (DESKTOP_SESSION). There is no need to create a new non-standard "DE" environment variable to accomplish the same thing.

**Comment by beanpole135** [comment]
The xdg-open utility should already be using the standardized XDG_CURRENT_DESKTOP or DESKTOP_SESSION environment variables to determine which DE is running. That is what it does on all the BSD's already, but I have heard that many OS's and/or distros distribute modified versions of the "xdg-open" script due to a lack of changes from the upstream project.

Another alternative is to just replace the xdg-open script with a symlink to lumina-open instead. That will actually avoid all the extra overhead and mangling of inputs that xdg-open does to the inputs as well.

**Comment by beanpole135** [comment]
Looks like xdg-open does in fact use the XDG_CURRENT_DESKTOP environment variable for determining which desktop is running: https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-utils-common.in (look at the "detectDE()" function).

Perhaps the upstream tool just needs to have the logic to detect "Lumina" as the DE in that function and have it launch lumina-open instead.

**Comment by rodlie** [comment]
You can override desktop in xdg-open with DE=

But, xdg-open must support Lumina (lumina-open) to work, so upstream needs to be aware of Lumina (I did a push request to xdg-utils, but they don't accept github requests).

As far as I am aware most distros ship unmodified xdg-utils.

**Pull request closed without merging**
