### PR TITLE
Add menu to create new directory in lumina-fm

### PR DESCRIPTION
**Pull request by lbartoletti**
Even if it is possible to create a folder with the shortcut or a right click, I am a little confused not to have an action in the menu like in other FM.

This PR proposes its addition while keeping the shortcut Ctrl+Shift+N

A future improvement may be to add the creation of files in the menu.

### CODE REVIEW

**Comment by lbartoletti** [comment]
Oops... indentation seems different...

**Comment by q5sys** [comment]
Thanks for the PR!!
We do have this in the menu already... (see pic below) but Ken and I will look over what you've got and see if you're method is better than what we're currently using.
photo_2018-11-09_18-49-47

**Comment by lbartoletti** [comment]
Yes, you can create with the right click. I propose to add also a menu for that like some other FM like Thunar :)

**Comment by lbartoletti** [comment]
In fact. Both methods should be present

**Pull request merged**
