### PR TITLE
Missing LuminaPDF::LRUCache::contains() method causing compilation error

### PR DESCRIPTION
**Pull request by maxsteciuk**
Fix for https://github.com/lumina-desktop/lumina/issues/662

### CODE REVIEW

**Comment by q5sys** [comment]
I can confirm that this does fix the compilation error.  But pdf do not open.
May or may not be related to this patch or another issue.

**Comment by maxsteciuk** [comment]
Separate issue 
Seems related to optimization and parallelization of page rendering code such as keeping track of pages.size() vs pagesStillLoading counter

**Comment by q5sys** [comment]
I just wanted to leave it open for Ken to review and make the decision on.

**Comment by beanpole135** [comment]
Closing PR. Overcome by events. 
The poppler backend has already been redone to ensure rapid loading of pages without overloading the page cache.

**Pull request closed without merging**
