### PR TITLE
Fix the link to the Lumina RSS feed

### PR DESCRIPTION
**Pull request by nyanster**
The current one is broken.

### CODE REVIEW

**Comment by beanpole135** [comment]
The RSS feed link is actually fine - it was a problem with following the redirect from the "?feed=rss" query. This issue was already fixed on the current version of Lumina in source and it works fine with the current feed URL.

**Comment by nyanster** [comment]
But, why should the redirect have to happen in the first place? Why not just link to where the redirect points to? I'm curious.

**Comment by beanpole135** [comment]
Because the Lumina website is currently a Wordpress site, using that query lets the link "float" to new URL's later if wordpress decides to change the URL for it's auto-generated RSS feeds. I have run into changes like that before and this allows Lumina to dynamically react to those changes from the upstream sites.

**Comment by nyanster** [comment]
Good reason.  Thank you for explaining. :D

**Pull request closed without merging**
